# https://github.com/scala-steward-org/scala-steward/pull/2714
pullRequests.grouping = [
  {
    name = "scalatest"
    filter = [
      {"group" = "org.scalatest"}
      {"group" = "org.scalatestplus"}
    ]
  }
]

updates.pin  = [
  {
    # keep LTS version
    # https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html
    groupId = "org.scala-lang"
    artifactId = "scala3-library"
    version = "3.9."
  }
]

updates.ignore = [
  {
    groupId = "com.h2database"
  }
]

updates.fileExtensions = [
  ".scalafmt.conf"
  ".conf"
  "build.properties"
  ".scala"
  ".sbt"
  ".yml"
  ".md"
  ".markdown"
  ".txt"
  ".bat"
  ".sh"
]

postUpdateHooks = [
  {
    command = ["sbt", "updateScalikejdbcCliSetupScriptSbt"],
    commitMessage = "update sbt version",
    groupId = "org.scala-sbt",
    artifactId = "sbt"
  }
]
